# Generated by Django 5.0.7 on 2024-10-20 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_cascade_category_tag_cars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CASCADE',
        ),
        migrations.DeleteModel(
            name='Features',
        ),
        migrations.DeleteModel(
            name='Lates',
        ),
    ]
