# Generated by Django 5.0.7 on 2024-10-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_cascade_delete_features_delete_lates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='img',
        ),
        migrations.AddField(
            model_name='contact',
            name='contactemail',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
